# Included by CMakeLists

set(SLIC3R_APP_NAME "CaribouSlicer")
set(SLIC3R_APP_KEY "CaribouSlicer")
set(SLIC3R_APP_CMD "CaribouSlicer")
set(SLIC3R_VIEWER_CMD "CaribouGcodeviewer")
set(SLIC3R_VIEWER "caribou-gcodeviewer")
set(SLIC3R_VERSION "2.9.1")
set(SLIC3R_BUILD_NR "26398")
set(SLIC3R_BUILD_ID "CaribouSlicer-${SLIC3R_VERSION} Build: ${SLIC3R_BUILD_NR} based on PrusaSlicer and SuperSlicer")
set(SLIC3R_RC_VERSION "2,9,1,0")
set(SLIC3R_RC_VERSION_DOTS "2.9.1.0")

# remember to update /src/libslic3r/libslic3r.h !!!!!
